export const UtilRoutes = {
  LOGIN: '/auth',
  REGISTER: '/auth/register',
  PANEL: '/profile',
  DONATE: '/donate',
  HOME: '/',
  EVENTS: '/events',
  HELP: '/help',
  ABOUT: '/about',
  CONFIGURATION: '/configuration',
  ACHIEVEMENTS: '/achievements',
  BENEFITS: '/benefits',
  LOGOUT: '/logout',
  PRIVACY: '/privacy',
  TERMS: '/terms',
}
